# Biodiversity & Habitat (BDH) Analysis – Clean & Robust ----------------------------------
# Author: auto-generated by Cascade (2025-07-17)
# This version focuses on simplicity, reproducibility, and robustness.
# It trains a single Random-Forest (ranger) classifier on BDH classes and
# logs the entire run to analysis_output/analysis_log.txt.
# -----------------------------------------------------------------------

# ---------------------- 0. Global options & logging ---------------------
options(stringsAsFactors = FALSE, warn = 2)   # convert warnings to errors
out_dir <- "analysis_output"
if (!dir.exists(out_dir)) dir.create(out_dir)
log_file <- file.path(out_dir, sprintf("analysis_log_%s.txt", format(Sys.time(), "%Y%m%d_%H%M%S")))
log_con  <- file(log_file, open = "wt")
 sink(log_con, split = TRUE)
cat("BDH Clean Analysis – started at", format(Sys.time()), "\n")

# ---------------------- 1. Package management ---------------------------
needed <- c("tidyverse", "caret", "rpart", "rpart.plot", "MLmetrics")
missing <- needed[!(needed %in% installed.packages()[, "Package"])]
if (length(missing)) {
  cat("Installing missing packages:", paste(missing, collapse = ", "), "\n")
  install.packages(missing, repos = "https://cran.rstudio.com", quiet = TRUE)
}
lapply(needed, require, character.only = TRUE)

# ---------------------- 2. Data load & validation -----------------------
input_csv <- "Data/epi2024_data.csv"
if (!file.exists(input_csv)) stop("Input file not found: ", input_csv)

data <- read_csv(input_csv, show_col_types = FALSE)

# Required columns -------------------------------------------------------
required_cols <- c("BDH", "EPI", "ECS", "FSH", "APO", "AGR")
missing_cols  <- setdiff(required_cols, names(data))
if (length(missing_cols)) stop("Missing columns: ", paste(missing_cols, collapse = ", "))

# Remove rows with missing BDH or feature values -------------------------
data <- data %>% select(all_of(required_cols)) %>% drop_na()
cat("Data rows after NA removal:", nrow(data), "\n")
if (nrow(data) < 50) stop("Not enough complete cases to train a model.")

# ---------------------- 3. Create BDH classes ---------------------------
breaks <- quantile(data$BDH, probs = c(0, 0.33, 0.66, 1), na.rm = TRUE)
data <- data %>%
  mutate(BDH_Class = cut(BDH, breaks = breaks,
                         labels = c("Low", "Medium", "High"),
                         include.lowest = TRUE)) %>%
  relocate(BDH_Class)
cat("Class distribution:\n"); print(table(data$BDH_Class))

# ---------------------- 4. Train/test split -----------------------------
set.seed(123)
train_idx <- createDataPartition(data$BDH_Class, p = 0.8, list = FALSE)
train_set <- data[train_idx, ]
test_set  <- data[-train_idx, ]

# ---------------------- 5. Model training (Decision Tree) -------------------
ctrl <- trainControl(method = "repeatedcv", number = 5, repeats = 3, # Using repeated CV
                     classProbs = TRUE,
                     summaryFunction = multiClassSummary,
                     verboseIter = FALSE)

cat("\nTraining Decision Tree (rpart)...\n")
# Temporarily relax warning level to allow caret to handle resampling warnings
old_warn <- getOption("warn"); options(warn = 1)

tree_model <- train(
  BDH_Class ~ ., data = train_set,
  method = "rpart",
  trControl = ctrl,
  tuneLength = 10 # Let caret find the best complexity parameter
)

# Restore warning level
options(warn = old_warn)
print(tree_model)

# ---------------------- 6. Evaluation -----------------------------------
preds <- predict(tree_model, test_set)
conf  <- confusionMatrix(preds, test_set$BDH_Class)
cat("\nConfusion matrix:\n"); print(conf$table)
cat("\nOverall Accuracy:", round(conf$overall["Accuracy"] * 100, 2), "%\n")

# ---------------------- 7. Plot tree & save model -------------------------
cat("\nPlotting decision tree...\n")
tree_plot_file <- file.path(out_dir, "decision_tree_plot.png")
png(tree_plot_file, width = 1200, height = 800)
rpart.plot(tree_model$finalModel, box.palette = "RdBu", shadow.col = "gray", nn = TRUE)
dev.off()
cat("Decision tree plot saved to", tree_plot_file, "\n")

model_rds <- file.path(out_dir, "dt_bdh_model.rds")
saveRDS(tree_model, model_rds)
cat("Model saved to", model_rds, "\n")

sink(NULL); close(log_con)
cat("Run complete. See log:", log_file, "\n")
